const options = {
	width: 2000,
	height: 1000,
	systems: [
		{
			id: 1,
			name: "Солнечная система",
			x: 300,
			y: 250,
			sector: "Сектор Альфа",
			size: 35,
			color: "#FFD700",
			celestialBodies: [
				{
					name: "Солнце",
					type: "Звезда",
					size: "huge",
					color: "#FFD700",
					orbit: 0,
				},
				{
					name: "Меркурий",
					type: "Планета",
					size: "small",
					color: "#A9A9A9",
					orbit: 0.4,
					gravity: 0.38,
					temperature: 167,
				},
				{
					name: "Венера",
					type: "Планета",
					size: "medium",
					color: "#E6C229",
					orbit: 0.7,
					gravity: 0.91,
					temperature: 464,
				},
				{
					name: "Земля",
					type: "Планета",
					size: "medium",
					color: "#1E90FF",
					orbit: 1.0,
					gravity: 1.0,
					temperature: 15,
					moons: [
						{
							name: "Луна",
							type: "Спутник",
							size: "small",
							color: "#C0C0C0",
							orbit: 0.002,
							gravity: 0.16,
							temperature: -23,
						},
					],
				},
				{
					name: "Марс",
					type: "Планета",
					size: "medium",
					color: "#FF4500",
					orbit: 1.5,
					gravity: 0.38,
					temperature: -65,
					moons: [
						{
							name: "Фобос",
							type: "Спутник",
							size: "small",
							color: "#A9A9A9",
							orbit: 0.0001,
							gravity: 0.005,
							temperature: -100,
						},
						{
							name: "Деймос",
							type: "Спутник",
							size: "small",
							color: "#A9A9A9",
							orbit: 0.0002,
							gravity: 0.003,
							temperature: -100,
						},
					],
				},
			],
		},
		{
			id: 2,
			name: "Проксима Центавра",
			x: 700,
			y: 350,
			sector: "Сектор Альфа",
			size: 35,
			color: "#FF6347",
			celestialBodies: [
				{
					name: "Проксима Центавра",
					type: "Звезда",
					size: "medium",
					color: "#FF6347",
					orbit: 0,
				},
				{
					name: "Проксима b",
					type: "Планета",
					size: "medium",
					color: "#4682B4",
					orbit: 0.05,
					gravity: 1.2,
					temperature: -40,
				},
			],
		},
		{
			id: 3,
			name: "Альфа Центавра",
			x: 800,
			y: 150,
			sector: "Сектор Альфа",
			size: 35,
			color: "#FFA500",
			celestialBodies: [
				// ... (остальные данные о телах системы)
			],
		},
		// ... (другие системы)
	],
	paths: [
		{
			from: 1,
			to: 2,
		},
	],
}